[tool.poetry]
name = "chk-steam"
version = "0.1.0"
description = ""
authors = ["vilanele <vi77an@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
selenium = "^4.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
